name: Smart City Docker Compose

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Create environment file
      run: |
        cp env.example .env
        echo "DATABASE_URL=postgresql://postgres:password@postgres:5432/smart_city_db" >> .env
        echo "REDIS_URL=redis://redis:6379" >> .env
        echo "JWT_SECRET=your-secret-key" >> .env
        
    - name: Build and run with Docker Compose
      run: |
        docker-compose up --build -d
        
    - name: Wait for services to be ready
      run: |
        sleep 30
        docker-compose ps
        
    - name: Test API health
      run: |
        curl -f http://localhost:3001/api/health || exit 1
        
    - name: Test Frontend
      run: |
        curl -f http://localhost:3000 || exit 1
        
    - name: Cleanup
      if: always()
      run: |
        docker-compose down -v
